### ISSUE TITLE
can't detach from sabaki

### ISSUE THREAD

**Issue by jun63cn** [kaorahi/lizgoban#1]
![image](https://user-images.githubusercontent.com/30382868/41417321-8e69197a-701f-11e8-97f5-5f54e32d2245.png)
stand alone mode  I can't open a sgf file. It's no response.

**Comment by kaorahi** [comment]
Thanks for your bug report.  I do not know much about windows environment.

(detach)
I added a check for windows. Does it still happen in the latest version?

(open SGF)
1. Does it still happen in the latest version?
2. Which is your situation? (A) You get nothing by clicking "open..." button. (B) You get a file selection dialog, but it does not respond.
3. Would you try the equivalent short cut Ctrl-O?

**Comment by jun63cn** [comment]
Thanks for your reply. detach is working now.  I clicking "open..."button and get af file seletion dialog, then I select  a sgf file  the dialog disappear and noting happen.

**Comment by kaorahi** [comment]
Ah, "open" button was broken. I fixed it. thx!

**Comment by kaorahi** [comment]
For "this file is unreadable" in sabaki, would you try sabaki in new "dump_state2" branch (not "dump_state")?
https://github.com/kaorahi/Sabaki/tree/dump_state2

**Comment by jun63cn** [comment]
new dump_state2  still  has the same dialog.  Thank you very much!

**Comment by kaorahi** [comment]
I added debug prints to lizgoban and sabaki.
Would you try this if you can use a console on windows?
(Sorry for long instruction. I'd like to confirm the situation step by step
since I don't have a windows machine.)

(1) Check out the latest lizgoban (0eab8be).
(2) Build the latest sabaki in "dump_state2" branch (dc3cf3f) and put it as "external/sabaki" in lizgoban directory. https://github.com/kaorahi/Sabaki/tree/dump_state2
(3) Start lizgoban from command line as "npx electron src".
(4) Click "pause" button to stop pondering.
(5) Click "attach to sabaki" button.
(6) Search for the text "filename" backward in the console, and show me the text in the found line.
(7) Similarly, search for "temporary" and show me the text around the found line.

The results of (6) and (7) should be something like this.

    sabaki> sabaki_dump_state: {"filename":"/tmp/lizgoban-42738Wd4USvpAzxuq.sgf","m":["/tmp/lizgoban-42738Wd4USvpAzxuq.sgf#0","/tmp/lizgoban-42738Wd4USvpAzxuq.sgf","0"],"moveNumber":0}

    temporary file (/tmp/lizgoban-42738Wd4USvpAzxuq.sgf) for sabaki: (;KM[7.5]PW[]PB[])
    start sabaki: ["/home/foo/lizgoban/src/../external/sabaki",["/tmp/lizgoban-42738Wd4USvpAzxuq.sgf#0"]]

(8) Show me the contents of the printed SGF file (/tmp/lizgoban-42738Wd4USvpAzxuq.sgf in the above example). It should be "(;KM[7.5]PW[]PB[])".
(9) Detach sabaki and close lizgoban. Then, on the console, input the above command with replacing the SGF file name to a surely existing one. For example:

    /home/foo/lizgoban/src/../external/sabaki '/home/foo/bar.sgf#0'

What do you get?

**Comment by jun63cn** [comment]
Hi，
stderr|
stderr| 6397 visits, 2245185 nodes
stderr|
temporary file (C:\Users\ADMINI~1\AppData\Local\Temp\lizgoban-52680R4MJxjSBqIU.s
gf) for sabaki: (;KM[7.5]PW[]PB[])
start sabaki: ["D:\\lizgoban\\src/../external/sabaki",["C:\\Users\\ADMINI~1\\App
Data\\Local\\Temp\\lizgoban-52680R4MJxjSBqIU.sgf#0"]]
leelaz> 4 showboard
queue> showboard
stdout| =4
stdout|
stderr|
stderr| Passes: 0            Black (X) Prisoners: 0
stderr| Black (X) to move    White (O) Prisoners: 0
stderr|
stderr|    a b c d e f g h j k l m n o p q r s t
stderr| 19 . . . . . . . . . . . . . . . . . . . 19
stderr| 18 . . . . . . . . . . . . . . . . . . . 18
stderr| 17 . . . . . . . . . . . . . . . . . . . 17
stderr| 16 . . . + . . . . . + . . . . . + . . . 16
stderr| 15 . . . . . . . . . . . . . . . . . . . 15
stderr| 14 . . . . . . . . . . . . . . . . . . . 14
stderr| 13 . . . . . . . . . . . . . . . . . . . 13
stderr| 12 . . . . . . . . . . . . . . . . . . . 12
stderr| 11 . . . . . . . . . . . . . . . . . . . 11
stderr| 10 . . . + . . . . . + . . . . . + . . . 10
stderr|  9 . . . . . . . . . . . . . . . . . . .  9
stderr|  8 . . . . . . . . . . . . . . . . . . .  8
stderr|  7 . . . . . . . . . . . . . . . . . . .  7
stderr|  6 . . . . . . . . . . . . . . . . . . .  6
stderr|  5 . . . . . . . . . . . . . . . . . . .  5
stderr|  4 . . . + . . . . . + . . . . . + . . .  4
stderr|  3 . . . . . . . . . . . . . . . . . . .  3
stderr|  2 . . . . . . . . . . . . . . . . . . .  2
stderr|  1 . . . . . . . . . . . . . . . . . . .  1
stderr|    a b c d e f g h j k l m n o p q r s t
stderr|
stderr| Hash: 9A930BE1616C538E Ko-Hash: A14C933E7669946D
stderr|
stderr| Black time: 01:00:00
stderr| White time: 01:00:00
stderr|
sabaki>
sabaki> sabaki_dump_state: {"treePosition":[{"current":null,"id":1,"nodes":[{}],
"parent":null,"subtrees":[]},0]}
leelaz> 5 clear_board
queue> clear_board
queue> showboard
stdout| =5
leelaz> 6 showboard
stdout|
stderr|
stderr| Passes: 0            Black (X) Prisoners: 0
stderr| Black (X) to move    White (O) Prisoners: 0
stderr|
stderr|    a b c d e f g h j k l m n o p q r s t
stderr| 19 . . . . . . . . . . . . . . . . . . . 19
stdout| =6
stdout|
stderr| 18 . . . . . . . . . . . . . . . . . . . 18
stderr| 17 . . . . . . . . . . . . . . . . . . . 17
stderr| 16 . . . + . . . . . + . . . . . + . . . 16
stderr| 15 . . . . . . . . . . . . . . . . . . . 15
stderr| 14 . . . . . . . . . . . . . . . . . . . 14
stderr| 13 . . . . . . . . . . . . . . . . . . . 13
stderr| 12 . . . . . . . . . . . . . . . . . . . 12
stderr| 11 . . . . . . . . . . . . . . . . . . . 11
stderr| 10 . . . + . . . . . + . . . . . + . . . 10
stderr|  9 . . . . . . . . . . . . . . . . . . .  9
stderr|  8 . . . . . . . . . . . . . . . . . . .  8
stderr|  7 . . . . . . . . . . . . . . . . . . .  7
stderr|  6 . . . . . . . . . . . . . . . . . . .  6
stderr|  5 . . . . . . . . . . . . . . . . . . .  5
stderr|  4 . . . + . . . . . + . . . . . + . . .  4
stderr|  3 . . . . . . . . . . . . . . . . . . .  3
stderr|  2 . . . . . . . . . . . . . . . . . . .  2
stderr|  1 . . . . . . . . . . . . . . . . . . .  1
stderr|    a b c d e f g h j k l m n o p q r s t
stderr|
stderr| Hash: 9A930BE1616C538E Ko-Hash: A14C933E7669946D
stderr|
stderr| Black time: 01:00:00
stderr| White time: 01:00:00
stderr|
sabaki> sabaki_dump_state: {"treePosition":[{"current":null,"id":1,"nodes":[{}],
"parent":null,"subtrees":[]},0]}
leelaz> 7 clear_board
queue> clear_board
queue> showboard
stdout| =7
leelaz> 8 showboard
stdout|
stderr|
stderr| Passes: 0            Black (X) Prisoners: 0
stderr| Black (X) to move    White (O) Prisoners: 0
stderr|
stderr|    a b c d e f g h j k l m n o p q r s t
stderr| 19 . . . . . . . . . . . . . . . . . . . 19
stdout| =8
stdout|
stderr| 18 . . . . . . . . . . . . . . . . . . . 18
stderr| 17 . . . . . . . . . . . . . . . . . . . 17
stderr| 16 . . . + . . . . . + . . . . . + . . . 16
stderr| 15 . . . . . . . . . . . . . . . . . . . 15
stderr| 14 . . . . . . . . . . . . . . . . . . . 14
stderr| 13 . . . . . . . . . . . . . . . . . . . 13
stderr| 12 . . . . . . . . . . . . . . . . . . . 12
stderr| 11 . . . . . . . . . . . . . . . . . . . 11
stderr| 10 . . . + . . . . . + . . . . . + . . . 10
stderr|  9 . . . . . . . . . . . . . . . . . . .  9
stderr|  8 . . . . . . . . . . . . . . . . . . .  8
stderr|  7 . . . . . . . . . . . . . . . . . . .  7
stderr|  6 . . . . . . . . . . . . . . . . . . .  6
stderr|  5 . . . . . . . . . . . . . . . . . . .  5
stderr|  4 . . . + . . . . . + . . . . . + . . .  4
stderr|  3 . . . . . . . . . . . . . . . . . . .  3
stderr|  2 . . . . . . . . . . . . . . . . . . .  2
stderr|  1 . . . . . . . . . . . . . . . . . . .  1
stderr|    a b c d e f g h j k l m n o p q r s t
stderr|
stderr| Hash: 9A930BE1616C538E Ko-Hash: A14C933E7669946D
stderr|
stderr| Black time: 01:00:00
stderr| White time: 01:00:00
stderr|
sabaki> sabaki_dump_state: {"treePosition":[{"current":null,"id":3,"nodes":[{"AP
":["Sabaki:0.34.1"],"CA":["UTF-8"],"DT":["2018-06-17"],"FF":["4"],"GM":["1"],"KM
":["7.5"],"SZ":["19"]}],"parent":null,"subtrees":[]},0]}
leelaz> 9 clear_board
queue> clear_board
queue> showboard
stdout| =9
leelaz> 10 showboard
stdout|
stderr|
stderr| Passes: 0            Black (X) Prisoners: 0
stderr| Black (X) to move    White (O) Prisoners: 0
stderr|
stderr|    a b c d e f g h j k l m n o p q r s t
stderr| 19 . . . . . . . . . . . . . . . . . . . 19
stderr| 18 . . . . . . . . . . . . . . . . . . . 18
stdout| =10
stdout|
stderr| 17 . . . . . . . . . . . . . . . . . . . 17
stderr| 16 . . . + . . . . . + . . . . . + . . . 16
stderr| 15 . . . . . . . . . . . . . . . . . . . 15
stderr| 14 . . . . . . . . . . . . . . . . . . . 14
stderr| 13 . . . . . . . . . . . . . . . . . . . 13
stderr| 12 . . . . . . . . . . . . . . . . . . . 12
stderr| 11 . . . . . . . . . . . . . . . . . . . 11
stderr| 10 . . . + . . . . . + . . . . . + . . . 10
stderr|  9 . . . . . . . . . . . . . . . . . . .  9
stderr|  8 . . . . . . . . . . . . . . . . . . .  8
stderr|  7 . . . . . . . . . . . . . . . . . . .  7
stderr|  6 . . . . . . . . . . . . . . . . . . .  6
stderr|  5 . . . . . . . . . . . . . . . . . . .  5
stderr|  4 . . . + . . . . . + . . . . . + . . .  4
stderr|  3 . . . . . . . . . . . . . . . . . . .  3
stderr|  2 . . . . . . . . . . . . . . . . . . .  2
stderr|  1 . . . . . . . . . . . . . . . . . . .  1
stderr|    a b c d e f g h j k l m n o p q r s t
stderr|
stderr| Hash: 9A930BE1616C538E Ko-Hash: A14C933E7669946D
stderr|
stderr| Black time: 01:00:00
stderr| White time: 01:00:00
stderr|

**Comment by kaorahi** [comment]
Hi.
This log suggests that your sabaki is not the latest version in [dump_state2](https://github.com/kaorahi/Sabaki/tree/dump_state2).
Would you confirm it?
You should have lines like this:

    sabaki> This is a customized sabaki (dump_state2).
    sabaki> argv = ["/home/foo/bar/baz/sabaki","/tmp/lizgoban-42738Wd4USvpAzxuq.sgf#0"]

**Comment by jun63cn** [comment]
sorry it's my fault I build the latest sabaki in "dump_state2" branch (dc3cf3f) but only substitute the old sabaki.exe. now put the" dist " in“ external/sabaki”   and everyting is OK now.   Thanks for your patience!
