### ISSUE TITLE
Add "Open recent" menu

### ISSUE THREAD

**Issue by kaorahi** [kaorahi/lizgoban#101]
(continued from https://github.com/kaorahi/lizgoban/issues/70#issuecomment-1833190944 )

If you're interested in having your name recorded in the official Git repository, feel free to send a pull request. If not, I will make a commit myself. In both cases, I will also add your name to contributors.html, accessible through the Help > Contributors menu.

Additionally, I'm planning to extend this feature. Beyond just recently opened files, I also want to include recently deleted boards, so that I won't need to repeatedly press Ctrl-Z (Edit > Undelete board) when there are many candidates.

**Comment by qcgm1978** [comment]
The "recently deleted boards" feature you mentioned is the same as what I want to implement as the "open recent files" feature. Are they the same? If they are, then it's just one feature.

I've already commited pr #102

**Comment by kaorahi** [comment]
Implemented in #102.
