### ISSUE TITLE
Why is the pasted tsumego image not displayed? 

### ISSUE THREAD

**Issue by qcgm1978** [kaorahi/lizgoban#106]
I'm trying to solve tsumego problems using this app, but when pasting the tsumego image, it shows up as gray and the tsumego position is not displayed. The effect and image are shown below:

update: Do I need to drag the img into gray area? It displays if I drag it but the stones aren't recognized correctly.
<img width="947" alt="截屏2023-12-14 13 24 18" src="https://github.com/kaorahi/lizgoban/assets/3024299/c1292c28-2f6e-40c2-9fff-d5b500713c7f">

<img width="1382" alt="截屏2023-12-14 11 10 52" src="https://github.com/kaorahi/lizgoban/assets/3024299/cbdb78e2-d24b-441e-baa1-5c1dce692c97">
<img width="259" alt="截屏2023-12-14 11 04 37" src="https://github.com/kaorahi/lizgoban/assets/3024299/21781c28-1208-464e-b9c3-6441eb29bc06">

**Comment by kaorahi** [comment]
The gray screen suggests that something isn't working properly.

This works for me:

1. Open this page on Chromium, right-click the tsumego diagram image, and select "Copy image".
2. In this app, select [Edit] > [Paste] from the menu bar.
3. Then, the diagram image appears in the "SGF from Image" window.

**Comment by qcgm1978** [comment]
I copied the files wrongly. I directly copied the image files from Finder, which may not be supported. Now I'm able to solve the tsumego problems, thank you very much!

**Comment by qcgm1978** [comment]
I found the app only support copying the contents of the SGF or IMG file instead of the file directly. It seems should prompt user about the error as the following code:
```javascript
function paste_sgf_or_url_from_clipboard() {
    const s = clipboard.readText(1);
    if (/\.\w{0,5}$/.test(s)) {
        return toast('Please copy the contents of the SGF or IMG file instead of copying the file directly.',3000)
    }
    ...
}
```

**Comment by kaorahi** [comment]
Could you explain this in detail? I'd like to know:

1. OS
2. Specific mouse/keyboard actions to reproduce the issue, including the exact meaning of "copying the file directly"
3. Example values of `clipboard.readText()` and `clipboard.readText(1)` in this situation

By the way, is `clipboard.readText(1)` correct? Do you mean `clipboard.readText('selection')`?

https://www.electronjs.org/docs/latest/api/clipboard

**Comment by qcgm1978** [comment]
* 1, Mac 
* 2, Cmd+C selected file(img or sgf) in finder.
* 3, `clipboard.readText()`, `clipboard.readText(0)`, `clipboard.readText('selection')` and `clipboard.readText(1)` all return the same file name copied such as `122706.sgf`, `李维清-伊凌涛.png`

So I think it is not supported that copy the file in find(Mac folder) directly.

**Comment by kaorahi** [comment]
Would you try this in `paste_sgf_or_url_from_clipboard()`?

`
console.log(clipboard.availableFormats().map(fmt => [fmt, clipboard.read(fmt)]))
`

If we can obtain the full path of the file, it is better to open the file directly rather than to show an error message. We may need to use a library to detect the file type for this approach.

https://www.npmjs.com/package/file-type

**Comment by qcgm1978** [comment]
Very correct, your words inspired me to find a solution. You need to first determine whether the content of the clipboard is a sgf or img file name, and then obtain the file path. The code is as follows:
```
function get_path_by_name() {
    const buffer = clipboard.readBuffer('public.file-url')
    const filePath = buffer.toString('utf-8')
    return filePath
}
function is_img(p) {
    return p.match(/(jpg|jpeg|gif|png|webp)$/i);
}
function paste_sgf_or_url_from_clipboard() {
    let s = clipboard.readText(1);
    // However, there is a problem. If the copied image file does not display the extension, it cannot be determined whether it is an image file.
    if (s.endsWith('.sgf') || is_img(s)) {
        s = get_path_by_name()
        if (s.match('^(file|https?)://')) {
            open_url(s)
        } else {
            read_sgf(s)
        }
    } else {
        if (!clipboard.readImage().isEmpty()) {
            open_clipboard_image();
            return
        }
    }
}
```

**Comment by qcgm1978** [comment]
`clipboard.readImage().isEmpty()` can't check whether the copied is img on mac. If the copied is a sgf file, this method would still return true. It may still need to check the result of read(mac_url). For example change to the following code:
```
function paste_sgf_or_url_from_clipboard() {
    // clipboard.has and clipboard.read are experimental in Electron v28 [2024-02-02]
    const read = format => clipboard.has(format) && clipboard.read(format)
    const mac_url = 'public.file-url'  // for Cmd-C on Finder (Mac)
    const mac_s = read(mac_url);
    const s = mac_s || clipboard.readText()
    if (mac_s=='' && !clipboard.readImage().isEmpty()) {open_clipboard_image(); return}
    s.match('^(file|https?)://') ? open_url(s) : read_sgf(s)
}
```

**Comment by kaorahi** [comment]
Thanks for pointing that out. Does this work for various cases?

```
--- a/src/main.js
+++ b/src/main.js
@@ -2126,6 +2126,9 @@ function copy_sgf_to_clipboard(cache_suggestions_p) {
     clipboard.writeText(game.to_sgf(cache_suggestions_p)); wink()
 }
 function paste_sgf_or_url_from_clipboard() {
+    // clipboard.read is experimental in Electron v28 [2024-02-02]
+    const mac_url = clipboard.read('public.file-url')  // for Cmd-C on Finder (Mac)
+    if (mac_url) {open_url(mac_url); return}
     if (!clipboard.readImage().isEmpty()) {open_clipboard_image(); return}
     const s = clipboard.readText(); s.match('^(file|https?)://') ? open_url(s) : read_sgf(s)
 }
```

* (Case A) Open this issue page on Chrome or Safari. Ctrl-click the tsumego diagram image and select "Copy image".
* (Case B) Open this issue page on Chrome or Safari. Ctrl-click [this link](https://www.red-bean.com/sgf/examples/ff4_ex.sgf) and select "Copy link".
* (Case C) Open this issue page on Chrome or Safari. Click and drag your mouse over this SGF text `(;SZ[19];B[qd];W[cd])` to select it. Push Cmd-C.
* (Case D) On Finder, click an SGF file and push Cmd-C.
* (Case E) On Finder, click an image file and push Cmd-C.

**Comment by qcgm1978** [comment]
Yes. All the five cases work.

**Comment by kaorahi** [comment]
fixed
