### ISSUE TITLE
Can we go back to the sgf_from_image page again?

### ISSUE THREAD

**Issue by qcgm1978** [kaorahi/lizgoban#111]
When I use the Paste image function, I often find that the generated sgf is incorrect. I want to have the option to go back to the sgf_from_image page and make changes. Currently, the page closes when I click OK. It would be better if the page was hidden instead of closed, and then reopened when needed. In addition to adding an option in the app menu, a right-click menu with an editing option could also be considered for the page.

Here is a demonstration of the function and the core code:

https://github.com/kaorahi/lizgoban/assets/3024299/6a4d45f0-477d-4ab3-bf56-99566b64f41e

```javascript
// hide page window
if (image_win && image_win.isVisible()) {
    image_win.hide()
}
// context menu
menu = new Menu();
const items = [{
    label: lang.edit,
    click: () => {
        image_win.show()
},
},...];
items.forEach(item => {
    menu.append(new MenuItem(item));
});
mainWindow.contextMenu = menu;
```

**Comment by kaorahi** [comment]
Sounds nice. I prefer everything be undoable.

I've implemented this locally and will push it after dogfooding for a while.

Also, a free-editing feature is already available. Place a black or white stone using `b` key + click or `w` key + click. To remove an existing stone, press either `b` or `w` key and click on it. This is described in the Help section under Display > Board > Mouse controls.

**Comment by qcgm1978** [comment]
I noticed the keyboard shortcuts for adding and removing stones, but I think it's easier to use the mouse to do it directly on the page. This is because it's more in line with the WYSIWYG principle, which means what you see is what you get.

**Comment by qcgm1978** [comment]
I discovered that it is important to call `read_sgf` in sgf_from_image page depending on the situation. Otherwise, it will always create a new board, for example:
```javascript
// main.js
image_win.show()
image_win.webContents.send('set_new_window', false);

// sgf_from_image.js
function set_new_window(dummy_ipc_event, bool) {
    is_new_window=bool
};
function finish_electron() {
    ...
    is_new_window && send('read_sgf', sgf)
```

**Comment by kaorahi** [comment]
implemented
