### ISSUE TITLE
About "attach LizGoban to Sabaki" feature

### ISSUE THREAD

**Issue by qcgm1978** [kaorahi/lizgoban#116]
I saw that the OBSOLETE.md file mentioned the "attach LizGoban to Sabaki" feature. I tried to use this feature, but I encountered some problems. I want to know if this feature is still available. My computer seems unable to successfully build the customized version of Sabaki you created. I would like to know if it is possible to modify the latest Sabaki codebase. I made some modifications, but they were not successful. If this feature is too difficult, maybe it can be implemented by receiving data on the server side and then using mimic to open it, as described in #61.

The main reason for wanting to attach LizGoban to Sabaki is that I consider this project to be more suitable as an analysis tool, while Sabaki can be used as an SGF browsing and editing tool. This way, a single project will not have to carry too many functions.

**Comment by kaorahi** [comment]
Though this feature still works on my machine, I've completely given up on its maintenance. I'm not sure whether the following changes are relevant for the latest version.

https://github.com/SabakiHQ/Sabaki/compare/master...kaorahi:dump_state2

**Comment by qcgm1978** [comment]
I modified Sabaki project and request local server api to send game info and move data when making moves, the python Django server start Lizgoban and call `set_game_info` and `play` api to map the moves. It works.
