### ISSUE TITLE
Is endstate_option deprecated? 

### ISSUE THREAD

**Issue by qcgm1978** [kaorahi/lizgoban#117]
According to the following code, it seems that `endstate_option` configured in config.json should be an array. However, this configuration is not mentioned in the project, which means it is no longer valid. Was it abandoned because it did not have obvious benefits? Since I want to modify this project locally to make it more in line with my ideas, I want to delete the invalid code.
```javascript
function start_endstate(given_start_args, endstate_option) {
    const [lz_command, x] = endstate_option
    ...
}
```

**Comment by kaorahi** [comment]
See OBSOLETE.md. :)

I'd like to remove the code for this obsolete feature to clean up the codebase someday (#46).

In the past, this hybrid approach using multiple engines was the only way for me to obtain strong moves and acceptable score estimations at the same time. Now, KataGo is absolutely preferred, offering both with better accuracy through a single engine, eliminating the hassle of managing multiple engines.

**Comment by qcgm1978** [comment]
Can it be understood that Leela Zero no longer requires support? [If so, that would significantly reduce the complexity of the code. I also rarely use Leela Zero.]

**Comment by kaorahi** [comment]
No. I'll keep supporting other GTP engines including Leela Zero, [Leela (patched)](https://github.com/leela-zero/leela-zero/issues/2631), and [TamaGo](https://github.com/kobanium/TamaGo). What I mentioned is a special variant of LZ equipped with an additional `endstate_map` command. Please refer to OBSOLETE.md for details.

Of course, you can remove their support from your fork freely.

**Comment by kaorahi** [comment]
I'm planning to delete `endstate_leelaz` soon (504b09dcb) and reuse its code for Human supervised learning net.

https://github.com/kaorahi/lizgoban/blob/humansl_proto1/README_HumanSL.md
