### ISSUE TITLE
error if no leelaz in external

### ISSUE THREAD

**Issue by ivysrono** [kaorahi/lizgoban#13]
![图片](https://user-images.githubusercontent.com/2649544/59552491-3ce76f00-8fba-11e9-9a1c-9b178eca4384.png)
![图片](https://user-images.githubusercontent.com/2649544/59552493-407af600-8fba-11e9-81cc-6038a35dc410.png)

config.json:
```
{
  "shortcut": [
    {
      "label": "LZ",
      "accelerator": "Ctrl + 1",
      "leelaz_command": "D:\\AI\\leela-zero\\leelaz.exe",
      "leelaz_args": ["-g", "-w", "D:\\AI\\Weights\\10B_ManKitPong"]
    },
    {
      "label": "minigo",
      "accelerator": "Ctrl + 2",
      "leelaz_command": "D:\\AI\\leela-zero\\leelaz.exe",
      "leelaz_args": ["-g", "-w", "D:\\AI\\Weights\\15B_LeelaMaster_GX89"]
    }
  ]
}
```

`npx electron src -c config.json`, then show errors and load by network.gz

load `10B_ManKitPong` while there is `leela.exe` in external.

**Comment by kaorahi** [comment]
I'll fix this. But please note that "shortcut" is quite experimental and undocumented. It may be changed in (near) future.
