### ISSUE TITLE
Adjustable komi?

### ISSUE THREAD

**Issue by isty2e** [kaorahi/lizgoban#15]
With the recent KataGo support, komi values other than 7.5 can be quite helpful for analysis, especially for games played in the last century. Is there any plan to support adjustable komi?

**Comment by kaorahi** [comment]
We already have "Komi" in "Tool" menu after 7c8e2709 :)
It appears only when you use KataGo.

**Comment by isty2e** [comment]
Cool! I pulled and built the latest version, and seems like it works without any problem. Closing this issue.
