### ISSUE TITLE
SyntaxError: Unexpected token K in JSON

### ISSUE THREAD

**Issue by kaorahi** [kaorahi/lizgoban#25]
(from https://github.com/kaorahi/lizgoban/issues/6#issuecomment-505676942)

This error indicates something wrong in *.json. You will need to replace every `\` with `\\` (or `/` simply) in the present case.

**Comment by ozymandias8** [comment]
I changed `\` to `\\` in katago.json, and still get an error in Windows 10. This one is a bit different.

> [Main Instruction]
> A JavaScript error occurred in the main process
> 
> [Content]
> Uncaught Exception:
> Error: Cannot find module 'tmp'
> Require stack:
> - C:\Users\shift\Documents\GitHub\lizgoban\src\main.js
> - C:\Users\shift\AppData\Roaming\npm-cache\_npx\3116\node_modules\electron\dist\resources\default_app.asar\main.js
> - 
>     at Module._resolveFilename (internal/modules/cjs/loader.js:659:15)
>     at Function.Module._resolveFilename (C:\Users\shift\AppData\Roaming\npm-cache\_npx\3116\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:43:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:577:27)
>     at Module.require (internal/modules/cjs/loader.js:715:19)
>     at require (internal/modules/cjs/helpers.js:14:16)
>     at Object.<anonymous> (C:\Users\shift\Documents\GitHub\lizgoban\src\main.js:49:13)
>     at Module._compile (internal/modules/cjs/loader.js:815:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
>     at Module.load (internal/modules/cjs/loader.js:677:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:609:12)

**Comment by kaorahi** [comment]
Thx for the advice. Unfortunately, I cannot write step-by-step instructions by myself since I have no Windows machine.

You can ignore the warnings on iconv-lite and jschardet.
https://github.com/SabakiHQ/sgf/issues/4#issuecomment-493634635
