### ISSUE TITLE
Feature request: AI tests

### ISSUE THREAD

**Issue by ivysrono** [kaorahi/lizgoban#26]
Related with #23 

We need to test AIs and get results like: https://github.com/leela-zero/leela-zero/issues/2431#issuecomment-504797442

So, would you support:
- Start AI VS AI limit( 100 for example ) or unlimit ( end by human ) plays.
- Save sgfs auto by titles like `DateTime-Black-*pos-win-White-*pos` and so on.

**Comment by kaorahi** [comment]
It is out of the scope of this project. I don't hope lizgoban to be an almighty tool.
