### ISSUE TITLE
feature request: show endstate on every point

### ISSUE THREAD

**Issue by ivysrono** [kaorahi/lizgoban#27]
Newest Lizzie for KataGo:
![图片](https://user-images.githubusercontent.com/2649544/60186826-20bbbb80-985f-11e9-955d-05d11a711089.png)

**Comment by kaorahi** [comment]
implemented ("Score bar" in "View" menu, that appears only when KataGo is used)

**Comment by ivysrono** [comment]
@kaorahi I'd like to show score and winrate at the same time.

**Comment by kaorahi** [comment]
It will not be easy to read if we show both. In addition, Lizzie style is not maintained seriously.

**Comment by ivysrono** [comment]
Add settings?
Calculated amount is not important, in my opinion.

**Comment by kaorahi** [comment]
I'd like to keep settings as small as possible in this project. In my past project, I accepted almost all requests on various settings and they made debugging too difficult.

**Comment by ivysrono** [comment]
[](https://user-images.githubusercontent.com/2649544/60392256-821aad80-9b31-11e9-9054-4a8778953055.png)
Adjust the circle to a square may easy to read?
