### ISSUE TITLE
Little incompatibility with electron5+

### ISSUE THREAD

**Issue by ivysrono** [kaorahi/lizgoban#30]
```
  "dependencies": {
    "@sabaki/sgf": "^3.0.0",
    "electron": "^5.0.0",
    "electron-store": "^4.0.0",
    "tmp": "^0.1.0"
  }
```
![图片](https://user-images.githubusercontent.com/2649544/60385330-9e2f3800-9aba-11e9-8473-6eb8eb74963f.png)
No space to top.

**Comment by kaorahi** [comment]
Thx. I'll check it.

**Comment by kaorahi** [comment]
I also experienced the same problem. It seems that something is changed around fonts in Electron 5.

**Comment by kaorahi** [comment]
All texts are drawn on slightly upper positions in Electron 5. We need to adjust them.
https://stackoverflow.com/questions/53958949/createjs-canvas-text-position-changed-after-chrome-version-upgrade-from-70-to-71
https://bugs.chromium.org/p/chromium/issues/detail?id=607053

**Comment by ivysrono** [comment]
```
    "electron": "^6.0.0",
    "electron-store": "^4.0.0",
```
same issue.

**Comment by ivysrono** [comment]
Same issue with electron6.

**Comment by ivysrono** [comment]
Same issue with electron7.
