### ISSUE TITLE
Menu in OSX

### ISSUE THREAD

**Issue by alexpenson** [kaorahi/lizgoban#31]
I can't see the "Tool" menu on OSX, does this line need to go in somewhere?
```Menu.setApplicationMenu(menu)```
https://electronjs.org/docs/api/menu#menusetapplicationmenumenu
Thanks a lot

**Comment by kaorahi** [comment]
thx. I completely forgot Mac. Does 502abeaa work?

**Comment by alexpenson** [comment]
Yes awesome thanks!
