### ISSUE TITLE
Installer for Windows user

### ISSUE THREAD

**Issue by wonsiks** [kaorahi/lizgoban#32]
I made an installer for windows.

It contains various softwares, engines and weight files such as lizzie, LizGoban, Sabaki, leelazero, katago, minigo, ELF OpenGo, PhoenixGo and LeelaMaster series.

You can use all of them by one click installing.
Please note that you need Graphic Card on your computer to use those softwares.

Enjoy...

https://github.com/wonsiks/BadukMegapack

![megapack](https://user-images.githubusercontent.com/37356450/64949224-ab86e200-d8b3-11e9-8238-58a417500e98.png)

**Comment by kaorahi** [comment]
Thx! I hope users will enjoy the new feature of area counts.

**Comment by kaorahi** [comment]
added into README (b585fede)
