### ISSUE TITLE
Can't display anything at goban now.

### ISSUE THREAD

**Issue by jun63cn** [kaorahi/lizgoban#4]
windows7x64 using #2920595 commit .  #68a78d9 works well

**Comment by kaorahi** [comment]
thx for reporting. Do you see any error message by clicking [Debug] ==> [Toggle Developer Tools] (==> [Console] in the new pane)?

**Comment by jun63cn** [comment]
F:\lizgoban\node_modules\electron\dist\resources\electron.asar\renderer\security-warnings.js:259 Electron Deprecation Warning (nodeIntegration default change) This window has node integration enabled by default. In Electron 5.0.0, node integration will be disabled by default. To prepare for this change, set {nodeIntegration: true} in the webPreferences for this window, or ensure that this window does not rely on node integration and set {nodeIntegration: false}.
warnAboutNodeIntegrationDefault @ F:\lizgoban\node_modules\electron\dist\resources\electron.asar\renderer\security-warnings.js:259
F:\lizgoban\node_modules\electron\dist\resources\electron.asar\renderer\security-warnings.js:170 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
isUnsafeEvalEnabled.then @ F:\lizgoban\node_modules\electron\dist\resources\electron.asar\renderer\security-warnings.js:170

**Comment by kaorahi** [comment]
These warnings seem harmless. Then...

1. What is the version of your leelaz?
2. Would you try 'binary search' between 68a78d9 and 2920595 to find which commit caused the problem? (Does 0e1787f work? If yes, does e97cb83 work? ...)

**Comment by jun63cn** [comment]
my leelaz is 0.17
the commit #8238edb is not work. c8e7bcc works well. 
the debugger console of 8238edb7:
D:\lizgoban\node_modules\electron\dist\resources\electron.asar\renderer\security-warnings.js:259 Electron Deprecation Warning (nodeIntegration default change) This window has node integration enabled by default. In Electron 5.0.0, node integration will be disabled by default. To prepare for this change, set {nodeIntegration: true} in the webPreferences for this window, or ensure that this window does not rely on node integration and set {nodeIntegration: false}.
warnAboutNodeIntegrationDefault @ D:\lizgoban\node_modules\electron\dist\resources\electron.asar\renderer\security-warnings.js:259
D:\lizgoban\node_modules\electron\dist\resources\electron.asar\renderer\security-warnings.js:170 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
isUnsafeEvalEnabled.then @ D:\lizgoban\node_modules\electron\dist\resources\electron.asar\renderer\security-warnings.js:170
renderer.js:504 Uncaught TypeError: Cannot read property '15' of undefined
    at goto_idx_maybe (renderer.js:504)
    at play_here (renderer.js:475)
    at HTMLCanvasElement.canvas.onmousedown.e (renderer.js:358)
renderer.js:504 Uncaught TypeError: Cannot read property '12' of undefined
    at goto_idx_maybe (renderer.js:504)
    at play_here (renderer.js:475)
    at HTMLCanvasElement.canvas.onmousedown.e (renderer.js:358)

**Comment by kaorahi** [comment]
thx for your help on debug. I'd like to know a little more...

1. Does the problem happen with no operation from the start? Or, what are your operations before the problem?
2. Does the newly committed 6909bdb work?
3. Between 9c45272 and 5fe0290, would you try [Debug] ==> [Show 0-visits] and check whether it causes the problem?

**Comment by jun63cn** [comment]
1. npx electron src  then display goban has nothing on it.
2. the newly commited does't work. same as 2920595,35e4b79,8238edb
Thanks

**Comment by kaorahi** [comment]
I modified several doubtful codes. Does newly committed fe9e52a work? If no, would you try this?

1. "npx electron src" to Start lizgoban
2. Click [pause] button
3. Set [Debug] ==> [Debug log]
4. [File] ==> [Reset]
5. What is printed on your terminal (command prompt) after the above "npx electron src"?
6. Click [resume] button
7. What is printed on your terminal?

(my case: 5.)
~~~
$ npx electron src
6197.41 [10397] start leela zero: ["/home/xxx/lizgoban/src/../external/leelaz","-g","-w","/home/xxx/lizgoban/src/../external/network.gz"]
6197.41 [10441] queue> clear_board []
6197.41 [10441] queue> showboard [clear_board]
6197.41 [10441] queue> clear_board [clear_board,showboard]
6197.41 [10441] queue> showboard [clear_board,clear_board]
6197.43 [10441] stderr| Using 8 thread(s).
6197.43 [10441] stderr| RNG seed: 329372988488888673
6197.43 [10441] stderr| BLAS Core: built-in Eigen 3.3.7 library.
6197.81 [10441] stderr| Detecting residual layers...v1...192 channels...15 blocks.
6198.23 [10441] stderr| Initializing CPU-only evaluation.
6198.23 [10441] stderr| Setting max tree size to 4324 MiB and cache size to 480 MiB.
6198.23 [10441] leelaz>  0 lz-analyze interval 1 minmoves 30 [clear_board,clear_board,showboard]
6198.23 [10441] leelaz>  1 name [clear_board,clear_board,showboard]
6198.23 [10441] stdout| =0
6198.29 [10441] stderr| NN eval=0.442493
6198.45 [10441] stdout| info move D4 visits 1 winrate 4441 prior 1897 lcb 0 order 0 pv D4 info move Q4 visits 0 winrate 0 prior 1893 lcb 0 order 1 pv Q4 info move Q16 visits 0 winrate 0 prior 1890 lcb
 0 order 2 pv Q16 info move D16 visits 0 winrate 0[snip 1417] info move E17 visits 0 winrate 0 prior 8 lcb 0 order 26 pv E17 info move P17 visits 0 winrate 0 prior 8 lcb 0 order 27 pv P17 info move C1
5 visits 0 winrate 0 prior 8 lcb 0 order 28 pv C15 info move C5 visits 0 winrate 0 prior 8 lcb 0 order 29 pv C5
6198.55 [10441] stderr|
6198.55 [10441] stderr|  R16 ->       2 (V: 44.98%) (LCB:  0.00%) (N:  2.09%) PV: R16 D16
6198.55 [10441] stderr|  C16 ->       2 (V: 44.72%) (LCB:  0.00%) (N:  2.15%) PV: C16 Q16
... snip ...
6198.55 [10441] stderr|  Q16 ->       1 (V: 44.71%) (LCB:  0.00%) (N: 18.91%) PV: Q16
6198.55 [10441] stderr|  D16 ->       1 (V: 44.55%) (LCB:  0.00%) (N: 18.60%) PV: D16
6198.55 [10441] stderr| 2.2 average depth, 3 max depth
6198.55 [10441] stderr| 5 non leaf nodes, 2.40 average children
6198.55 [10441] stderr|
6198.55 [10441] stderr| 13 visits, 4677 nodes
6198.55 [10441] stderr|
6198.55 [10441] stdout|
6198.55 [10441] stdout| =1 Leela Zero
6198.55 [10441] leelaz>  2 clear_board [clear_board,showboard]
6198.55 [10441] stdout|
6198.55 [10441] stdout| =2
6198.55 [10441] leelaz>  3 clear_board [showboard]
6198.55 [10441] stdout|
6198.55 [10441] stdout| =3
6198.55 [10441] leelaz>  4 showboard []
6198.55 [10441] stdout|
6198.55 [10441] stdout| =4
6198.55 [10441] stdout|
6198.55 [10441] stderr|
6198.55 [10441] stderr| Passes: 0            Black (X) Prisoners: 0
6198.55 [10441] stderr| Black (X) to move    White (O) Prisoners: 0
6198.55 [10441] stderr|
6198.55 [10441] stderr|    a b c d e f g h j k l m n o p q r s t
6198.55 [10441] stderr| 19 . . . . . . . . . . . . . . . . . . . 19
6198.55 [10441] stderr| 18 . . . . . . . . . . . . . . . . . . . 18
... snip ...
6198.55 [10441] stderr|  2 . . . . . . . . . . . . . . . . . . .  2
6198.55 [10441] stderr|  1 . . . . . . . . . . . . . . . . . . .  1
6198.55 [10441] stderr|    a b c d e f g h j k l m n o p q r s t
6198.56 [10441] stderr|
6198.56 [10441] stderr| Hash: 9A930BE1616C538E Ko-Hash: A14C933E7669946D
6198.56 [10441] stderr|
6198.56 [10441] stderr| Black time: 01:00:00
6198.56 [10441] stderr| White time: 01:00:00
6198.56 [10441] stderr|
~~~

(my case: 7.)
~~~
6545.86 [10441] queue> lz-analyze interval 10 minmoves 30 []
6545.87 [10441] leelaz>  5 lz-analyze interval 10 minmoves 30 []
6545.88 [10441] stdout| =5
6545.88 [10441] stderr| NN eval=0.442493
6546.05 [10441] stdout| info move D16 visits 4 winrate 4444 prior 1860 lcb 2948 order 0 pv D16 Q4 R3 info move D4 visits 3 winrate 4430 prior 1897 lcb 0 order 1 pv D4 Q16 R17 info move Q4 visits 3 winrate 4435 prior 1893 lcb 0 order 2 pv Q4 D16 C17 i[snip 1487] info move E17 visits 0 winrate 0 prior 8 lcb 0 order 26 pv E17 info move P17 visits 0 winrate 0 prior 8 lcb 0 order 27 pv P17 info move C15 visits 0 winrate 0 prior 8 lcb 0 order 28 pv C15 info move C5 visits 0 winrate 0 prior 8 lcb 0 order 29 pv C5
6546.23 [10441] stdout| info move D16 visits 5 winrate 4445 prior 1860 lcb 3880 order 0 pv D16 Q4 R3 Q3 info move Q16 visits 5 winrate 4439 prior 1890 lcb 3853 order 1 pv Q16 D4 C3 C4 info move D4 visits 4 winrate 4422 prior 1897 lcb 2973 order 2 pv [snip 1530] info move E17 visits 0 winrate 0 prior 8 lcb 0 order 26 pv E17 info move P17 visits 0 winrate 0 prior 8 lcb 0 order 27 pv P17 info move C15 visits 0 winrate 0 prior 8 lcb 0 order 28 pv C15 info move C5 visits 0 winrate 0 prior 8 lcb 0 order 29 pv C5
... snip ...
~~~

**Comment by jun63cn** [comment]
Thanks you very much!  It's working well now.
