### ISSUE TITLE
auto-save?

### ISSUE THREAD

**Issue by Strappa71** [kaorahi/lizgoban#44]
Would it be possible to get an option of some kind of auto-save of .sgf-file every xx seconds?

**Comment by kaorahi** [comment]
"Undelete board" in Edit menu works across sessions now. So you can recover lost boards after unintentional quit. Is this enough for your purpose?

**Comment by Strappa71** [comment]
I need to check that out!

**Comment by kaorahi** [comment]
That's good. :-)

I don't know about "Baduk/LizGoban folder". Are you using BadukMegapack by @wonsiks? If so, I will release LizGoban-0.4.0-pre3 soon so that BadukMegapack will be updated. But I need at least a few days for testing before the release.

**Comment by Strappa71** [comment]
That's the default folder in which the megapack installs LizGoban.

I have no hurry at all. Thx for the fast response and addition of my suggestion.

**Comment by kaorahi** [comment]
Tough I said "soon", the source code has been modified actively after my previous comment due to bugs and new ideas in other topics. I need some "cooling down" period (a few weeks?) for stable release of -pre3...

**Comment by Strappa71** [comment]
I am in no hurry at all.

As long as it is included in some future release I am very happy.

The reason I asked for is that my silly cloud-PC provider that just shuts down after to long period of "human interaction". With autosave of SGF I can just log in againt at start up and resume.
