### ISSUE TITLE
A change in rules is globally applied

### ISSUE THREAD

**Issue by isty2e** [kaorahi/lizgoban#48]
As the title tells, any change in rules seems to be applied across the boards, unlike komi. For example, if board A is set to Chinese and changing focus to board B and setting rules to Japanese, board A is analyzed with Chinese rules.

**Comment by kaorahi** [comment]
not tested well...

Please let me know if you have SGF files whose RU properties are not mapped correctly to KataGo's rule names. (See [src/katago_rules.js](https://github.com/kaorahi/lizgoban/blob/master/src/katago_rules.js).)

**Comment by isty2e** [comment]
I haven't tested with SGF files neither, but at least rules are not global anymore, so I'm closing this issue.
