### ISSUE TITLE
How do I add my GPU in Win10?

### ISSUE THREAD

**Issue by GopherAl** [kaorahi/lizgoban#49]
Firstly, congratulations on a great product! 

My system is an AMD Ryzen 5-2400G with Radeon Vega Graphics 3.60 GHz running the latest Win10. 

I am unknowledgable about coding and haven't been able to get my GPU to work with LZ or KG. It works fine with Leela 0.11 Graphics Accelerated but not with any other go GUI. (With Leela the GPU uses about 4% GPU. With LizGoban running KataGo the GPU uses about 3% GPU. With Lizzie (Java Platform SE binary (32 bit)) the GPU uses about 0.4% GPU running KataGo and about 0.2% GPU running LeelaZero. So it appears to me that the GPU is not utilised by OpenCL because I would expect somewhere around 100% utilisation on my system if the engine was utilising the GPU.

I am seeking help with getting the GPU to run these engines. Thank you in advance for any help you can give me! (Any help with setting up Lizzie to utilise the GPU will also be gratefully received!)

In your Usage section you have:
**Case II: 64bit Windows with GPU

BadukMegapack by wonsiks may be the easiest way to install LizGoban together with many other tools. (Though it is not tested by the author of LizGoban, who does not have a Windows machine.)

Otherwise, see the release note to replace the built-in engines with GPU versions in Case I or follow the steps in Case III.**

1. The only release note I could find reads is repeated below. It doesn't mention replacing engines with GPU versions.
2. I also tried BadukMegapack. This tested the GPU and everything was fine. However LizGoban has the error _A Javascript error occurred in the main process_  and Lizzie does nothing when I try to open them from within BadukMegapack.

**RELEASE NOTE
LizGoban 0.4.0-pre2

    Upgrade the built-in engine of the all-in-one package to KataGo 1.3.2 (OpenCL) + 15 blocks network (g170e-b15c192-s1672).
    Upgrade libraries (Electron 8, etc.).
    Rename “aggressive KataGo” to “KataGo for handicap games” in “Preset” menu.
    Fix small bugs etc.

Links

Project Home / License (GPL3)**

**Comment by kaorahi** [comment]
Unfortunately, I cannot tell you step-by-step instructions since I have neither GPU nor Windows. Can anybody help us?

(1)
I recommend you to confirm whether LZ and KataGo work well without GUI in the first place. But I do not know how to do it on Windows...

(2)
Release notes of v0.4.0-pre* are incomplete as they are preview versions. "To customize it on 64bit Windows" is only written in that of v0.3.0. Sorry for inconvenience.
https://github.com/kaorahi/lizgoban/releases/tag/v0.3.0

~~~~
Prepare engines (Leela Zero and/or KataGo) by yourself, if necessary.
Download and extract the same all-in-one package as above.
Copy sample/config.json to the same folder as LizGoban *.exe and edit it. See README.html for its format.
~~~~

Anyway, you may want to to try (1) before (2).

(3)
Are there additional messages on "A Javascript error occurred in the main process"? I would like to know the details of "A Javascript error".

**Comment by GopherAl** [comment]
> (1)
I recommend you to confirm whether LZ and KataGo work well without GUI in the first place. But I do not know how to do it on Windows...
I don't know how to run them without GUI. 

>(2)
I will check that out tomorrow.

> (3)
Are there additional messages on "A Javascript error occurred in the main process"? I would like to know the details of "A Javascript error".
From within BadukMegapack, if I open LizGoban.exe I get these errors in this order:
![Java error 1](https://user-images.githubusercontent.com/47664082/76760876-36508700-67da-11ea-8d32-ae6876c8b624.png)
![Java error 2](https://user-images.githubusercontent.com/47664082/76760316-24baaf80-67d9-11ea-8621-196b474287a1.png)

**Comment by kaorahi** [comment]
Thanks. It seems that LizGoban failed to start the program `C:\Program Files\Baduk Megapack\...\leelaz` in your first screenshot. Does this file really exist?

@wonsiks, is this path correct for Megapack?

Before everything, we need to find a Windows user who knows the way of (1). Trying (2) without (1) is too hard.

**Comment by wonsiks** [comment]
@kaorahi I've checked what you asked.
It seems when the path contains space then some files aren't be copied to proper folder.
I'll try to fix this.
User can try not to change install folder then there'll not be problem.

**Comment by wonsiks** [comment]
@kaorahi I've fixed configuration error.
Now it's fine even when the install path contains space.
Cheers,

**Comment by kaorahi** [comment]
thx! > @wonsiks

**Comment by kaorahi** [comment]
It seems that this issue can be closed now.
cf. https://github.com/lightvector/KataGo/issues/173
