### ISSUE TITLE
[bug report] erron on Alternative weights for white

### ISSUE THREAD

**Issue by wonsiks** [kaorahi/lizgoban#5]
I've got the error message when I try to select a weight file for white.
I have no idea of what make this error.
Just check it up please.

LizGoban is a great tool.
Thank you for providing this excellent tool.

Wonsik Kim

![rizgoban_error](https://user-images.githubusercontent.com/37356450/58322867-36535500-7e5d-11e9-9c9b-a18442bda0fc.png)

**Comment by kaorahi** [comment]
Thx for the report. I got the same error when I selected an invalid weights file from "Tool" => "Alternative weights for white" menu.

1. What do you get if you select the same weights file from "File" => "Load network weights" menu?
2. Would you try the new version (3091575b)?

**Comment by wonsiks** [comment]
@kaorahi 
1. still shows error message
2. It works very well. Thank you... :)

**Comment by kaorahi** [comment]
Perhaps 4689b6fe solved it :)
