### ISSUE TITLE
Feature request: shortcut key for raw board and suggestion

### ISSUE THREAD

**Issue by lj739** [kaorahi/lizgoban#50]

**Comment by kaorahi** [comment]
Have you tried z key and shift+z key? The former shows/hides suggestions temporarily while it is pressed. The latter toggles the current view and the raw board. See "Help" menu for such shortcuts.

**Comment by kaorahi** [comment]
It's ok?

**Comment by lj739** [comment]
It is ok. Another question, when using katago as analyzing engine, there are rectangle marks on all stones. It makes the board looked not very clean.



在 2020-05-02 20:07:02，"kaorahi" <notifications@github.com> 写道：

It's ok?

**Comment by kaorahi** [comment]
You can uncheck [View] > [Ownership] in the menu. :)

**Comment by lj739** [comment]
these triangles are really annoying.







在 2020-05-07 20:45:13，"kaorahi" <notifications@github.com> 写道：

You can uncheck [View] > [Ownership] in the menu. :)
