### ISSUE TITLE
Question about Match vs. AI function...

### ISSUE THREAD

**Issue by wonsiks** [kaorahi/lizgoban#51]
I think this is a good idea and thanks for making this function...:)

I've got a quetion about logics of choosing weakened move.

In some cases winrates of 1st and 2nd best moves would be much different.
It means there's the ONLY move in some status.

In this case what move LizGoban choose?
If weakened move be chosen then AI's winrate will drop quickly.

**Comment by kaorahi** [comment]
Hi, @wonsiks san.

The best move will be selected if the second candidate is too bad. The range of "too bad" depends on the n in "weak n". The actual algorithm is rather complicated. See this function in `src/main.js` for details.

~~~~
function weak_move(weaken_percent) {
    // (1) Converge winrate to 0 with move counts
    // (2) Occasionally play good moves with low probability
    // (3) Do not play too bad moves
~~~~

As it was written for LZ in Oct. 2018, I'm afraid it may not be suitable for recent LZ and KataGo. We may need to tune it again for more interesting games. For example, I implemented another method in e62745c9 where KataGo tries to lose the score by X points in every move. Is it better?

**Comment by wonsiks** [comment]
Thank you for the reply.
It's good if AI doesn't play too bad move. It's great.
I don't think losing score for every moves is better if you understand.
Have good evening.
Thanks.

**Comment by kaorahi** [comment]
Oops, too stupid moves were selected by a bug. I fixed it in 619824ef and will release 0.4.1 for it.

**Comment by wonsiks** [comment]
@kaorahi Got it.... 👍

**Comment by kaorahi** [comment]
If we are still annoyed with too stupid moves, we may need to introduce another parameter "minimum visits" for avoiding them.

**Comment by kaorahi** [comment]
solved??

Anyway, KaTrain has better features in this field now. :)
