### ISSUE TITLE
Goishi-san mode (show ownerships of stones by face expressions)

### ISSUE THREAD

**Issue by kaorahi** [kaorahi/lizgoban#52]
Does anyone want to use this view seriously? I implemented it on my unpublished branch in a very crude manner. I need to brush up the code if I will support it officially.

The stone images are from https://www.asahi-net.or.jp/~hk6t-itu/igo/goisisan.html .
![goishisan](https://user-images.githubusercontent.com/38910552/82811326-75cadc00-9ecb-11ea-9305-65520e5a6dce.png)

**Comment by hebaeba** [comment]
This seems to be the Go stone of Mr.Tororo. I am well aware of this in the twitters.
I think it would be interesting to use this Go stone by switching it arbitrarily.

**Comment by kaorahi** [comment]
Yes. It is inspired from tororo2048's tweet :)

https://twitter.com/tororo2048/status/1261962761442955264

**Comment by kaorahi** [comment]
I'm not sure which face is suitable for which range of ownerships. Laughing faces are good at visibility for 100% safe stones. But they may be too "loud" in endgame...
![goishisan1](https://user-images.githubusercontent.com/38910552/83014986-ae4cf000-a05a-11ea-8568-859a4321a31e.png)
![goishisan2](https://user-images.githubusercontent.com/38910552/83014998-b3aa3a80-a05a-11ea-834f-0f0857ea9f5f.png)

**Comment by kaorahi** [comment]
Another version. This looks better for me. Thanks for new images, Tororo-san!
![goishisan3](https://user-images.githubusercontent.com/38910552/83140005-4d8be900-a128-11ea-9d4a-8adef500bc3c.png)
![goishisan4](https://user-images.githubusercontent.com/38910552/83140041-5e3c5f00-a128-11ea-86d5-1617ccda8947.png)

**Comment by hebaeba** [comment]
This new version is great!
Even for those who don't know Go, it's easy to understand.

**Comment by kaorahi** [comment]
released as v0.5.0-pre1
