### ISSUE TITLE
A possible glitch and a few suggestions

### ISSUE THREAD

**Issue by isty2e** [kaorahi/lizgoban#54]
1. When I start LizGoban with KataGo as the default engine, it says komi is set to 7.5 but it is actually 6.5, so I have to manually change komi to another value and back to 7.5. Has anyone else experienced the same?

2. I'd prefer to be able to set default komi values for even and handicap games; Especially, I'd like to set the default komi for handicap games as zero.

3. Can we have some bookmarks of the [rules, komi, handicap] combination, and use those templates when creating a new board? And I would be glad if those are configurable when opening a new board - just a personal preference.

**Comment by kaorahi** [comment]
I would like to confirm some points.

1. How did you know "it is actually 6.5"?

2. Do you mean the default komi for a new board? Or, is it the default komi for an SGF without "KM[...]"?

3. It may be easy for me to add the new parameters "rule", "komi", and "handicap" into "preset" in config.json so that you can switch them conveniently. Is this good for you?

~~~~
(example of config.json)
{
    ...
    "preset": [
        ...
        {
            "label": "H5", "accelerator": "Alt+F5",
            "rule": "tromp-taylor", "komi": 0, "handicap": 5,
            "empty_board": true, "match": "true"
        },
        ...
    ]
}
~~~~

**Comment by isty2e** [comment]
1. Winrate and scorelead.
2. Default komi for a new board.
3. That would suffice for me.

**Comment by kaorahi** [comment]
1. Fixed.

2. You can update the default komi for even (handicap) games if you change komi just after File > New empty board (New handicap game), respectively.

3. Not yet.

**Comment by isty2e** [comment]
I just pulled the update and bot 1 and 2 are properly working now.

**Comment by kaorahi** [comment]
3. Done. (I renamed "rule" in the above sample to "rules".)

Thx for suggestions. It may be better to show "Info" dialog automatically after "New empty board" for many users. But I'm not sure whether I like it or not...

**Comment by isty2e** [comment]
Hm, I expected it to be put elsewhere like File-Preset-..., just below File-New window. I think it can be configured in something like `preset-board` separated from `preset`. And I suppose a pane popping up when creating a new board for configuring [board size, handicap, rules, komi, handicap] will do, instead of currently separated entries of ["New empty board", "New handicap game", etc.].

**Comment by kaorahi** [comment]
Hmm... "Preset" can be used for various customization: engine configurations, view styles, game settings, etc. (and their mixtures). They are processed in a unified way and there is no reason to separate them into Engine-Preset, View-Preset, File-Preset, etc. on programmer's side. On user's side, I'm not sure whether such separations are worth additional complexity.

**Comment by isty2e** [comment]
Fine then. I'm already quite happy with the current status.

**Comment by kaorahi** [comment]
I implemented a configuration pane (File > New game). Would you test it?

**Comment by isty2e** [comment]
Looks good! Maybe adding incremental controls is even better? I have no idea what it is called exactly, but the thing appears upon hovering when changing komi or board size in the game info drawer pane in Sabaki.

**Comment by kaorahi** [comment]
done :)

**Comment by isty2e** [comment]
Closing the issue as the all the issues and suggestions are addressed.
