### ISSUE TITLE
Doesn't seem to work for me...

### ISSUE THREAD

**Issue by w3333** [kaorahi/lizgoban#55]
Installed latest node.js (12), followed instructions. Then I get
werner@linuxmint:~/Downloads/lizgoban$ npm start

> LizGoban@0.5.0-pre2 start /home/werner/Downloads/lizgoban
> electron .

(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
Gtk-Message: 16:22:47.146: GtkDialog mapped without a transient parent. This is discouraged.

Then there is another error message (see screenshot), and then the goban appears, but it doesn't seem to be in a working state (see screenshot).

Any ideas?

![Bildschirmfoto vom 2020-06-14 17-22-19](https://user-images.githubusercontent.com/24429753/84597350-b4690c00-ae63-11ea-9a91-3db6cba92916.png)
![Bildschirmfoto vom 2020-06-14 17-22-45](https://user-images.githubusercontent.com/24429753/84597352-b763fc80-ae63-11ea-8392-0ef0753688f4.png)

**Comment by kaorahi** [comment]
Probably you can ignore the warnings from Electron and Gtk. The dialog says that `/home/werner/Downloads/lizgoban/external/leelaz` seems missing. Did you skip this?

> 3. Put Leela Zero binary (version 0.17 or later) as `external/leelaz` together with its network weight as `external/network.gz`.

If you want to use KataGo, you have to write `config.json` instead of the above step. See "To configure it:" section in README for details.

**Comment by kaorahi** [comment]
solved??
