### ISSUE TITLE
order of R.suggest[]

### ISSUE THREAD

**Issue by rexl2018** [kaorahi/lizgoban#57]
Sometimes the R.suggest[0] doesn't seem to be better than R.suggest[1]/R.suggest[2]/R.suggest[3].

![image](https://user-images.githubusercontent.com/38375107/90849028-e8e7cf80-e3a0-11ea-8f70-15e80c1dc6f7.png)

During auto-analysis, if the R.suggest[0] is not the best one(or even quite bad one), one step might take long time to be finished.

**Comment by rexl2018** [comment]
Thank you very much for the explanation.
Would it be somewhat better if we watch the max in R.suggest[]?

**Comment by kaorahi** [comment]
Why do you think so?

I tried three criteria for auto-analysis.

* (A) Sum of visits over `R.suggest[]`
  * The engine searches in a constant time for every move.
  * The progress bar keeps a uniform pace.
* (B) Maximum of visits over `R.suggest[]`
  * The engine searches longer when there are many candidates.
  * The progress bar is slowed down or even stopped for a while in such cases.
* (C) Visits of `R.suggest[0]`
  * The engine searches further longer when it finds a new nice candidate.
  * The progress bar can even go back in such cases.

Then (C) seems desirable for me. Though the behavior of the progress bar is quite unnatural in (C), I can easily recognize what is occurring actually from the verbose winrate bar and the visits chart at the right bottom corner in LizGoban.

**Comment by rexl2018** [comment]
Or we can have a configuration for it?

**Comment by kaorahi** [comment]
Would you answer to my questions?

Anyway, I'd like to keep configurations as small as possible in this project. In my past project, I accepted almost all requests on various configurations and they made debugging too difficult. They tend to cause bugs that appear only in specific configurations and such bugs are often overlooked by the developers.

**Comment by rexl2018** [comment]
By using (B), as you said the search time will be close to constant, and normally the node with maximum visit is a good(sometimes best) candidate for next move even it is not R.suggest[0].
By using (C), there is small chance that the analysis takes quite long time. I encountered once many days ago, but I forgot which sgf I was using at that time.

Anyway, thanks a lot for sharing this powerful tool.
I will close the issue and let's focus on other important things.

**Comment by kaorahi** [comment]
Thanks for your reply. Please let me know if you notice problems that I may overlook. I have only a portable note PC and I cannot imagine what happens in heavy analyses with GPU.
