### ISSUE TITLE
Instructions for katago on mac

### ISSUE THREAD

**Issue by GimmeDatCode** [kaorahi/lizgoban#58]
The instructions in readme make a lot of assumptions. Some step by step for mac kata would be highly appreciated

**Comment by kaorahi** [comment]
What assumption, for example?

We need help from experienced Mac users for better documents anyway. Can anybody write some step-by-step instructions?

**Comment by GimmeDatCode** [comment]
it took me 25 minutes to figure out everything I needed..

1. That I needed to link my katago bin to external
2. An example cfg file

It should be runnable with much less steps. Thank you.

**Comment by kaorahi** [comment]
Thx for your suggestion. You don't need to put katago binary into `external/` if you write the correct path of katago in `config.json`.

I'm planning to add the following description into README. Does it help new users?

#### To use LizGoban with KataGo:

Follow the above 1 and 2. Place KataGo binary, its model, and its GTP configuration somewhere, say `/FOO/BAR/katago`, `/FOO/BAR/model.bin.gz`, and `/FOO/BAR/gtp.conf`. Then write `config.json` as follows.

~~~~
{
    "preset": [
        {
            "label": "KataGo",
            "engine": ["/FOO/BAR/katago", "gtp",
                       "-override-config", "analysisPVLen=50, defaultBoardSize=19",
                       "-model", "/FOO/BAR/model.bin.gz",
                       "-config", "/FOO/BAR/gtp.cfg"]
        }
    ]
}
~~~~

Start LizGoban as

    npm start -- -c config.json

(Windows: Put the above config.json into the same folder as lizgoban_windows.vbs and double-click lizgoban_windows.vbs.)
