### ISSUE TITLE
feature request: save image for current main board

### ISSUE THREAD

**Issue by rexl2018** [kaorahi/lizgoban#59]
It would be helpful if we can save image(png/jpg/svg) for what is being displayed in main board.

**Comment by kaorahi** [comment]
I'm not sure how convenient this feature is. Screen shots are enough for me at present. What is your use case?

You may prefer [q5go](https://github.com/bernds/q5Go) for your purpose. It has almost everything one will expect of Go tools!

**Comment by rexl2018** [comment]
Thanks a lot. 
I have modified the code of lizzie so that it can export svg.
However, I prefer lizgoban.

When I'm doing analysis, for some moves, I'd like to export the board as question and the principal variant as answer, and then print them out so that I can review in near future.

**Comment by kaorahi** [comment]
Have you tried "personal exercise book" feature in LizGoban? Push "!" to bookmark the board and push "?" to recall bookmarks randomly. (ref. [Tool] menu and "Tips" section in [Help])

**Comment by rexl2018** [comment]
Yes, the exercise feature is one of the reasons why I like lizgoban most!
Printing in paper is another way to help the reviewing, especially for my kids. :)

**Comment by kaorahi** [comment]
Ah, I agree. Thanks to the background story, this issue makes sense to me now. :)

We already have thumbnail functions in renderer.js that convert canvas to jpeg. Image exporter can be written in a similar way, I guess. The code before 29ced381 may be better for reference.

**Comment by rexl2018** [comment]
Thank you for the information. I will pick up a Javascript book and do it in my fork.

**Comment by kaorahi** [comment]
I added [Tool] > [Experimental] > [Save Q&A images] (shortcut key: PrintScreen) as it seems to be a fresh idea for Go tools. :)

But this is just an experiment. I'm not certain whether I will support it officially in future. Are there other users who like this feature?
