### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by kaorahi** [kaorahi/lizgoban#6]
I have no windows machine and I cannot build/check a windows binary by myself.

**Comment by kaorahi** [comment]
Is this an installer for windows? I cannot read details.
https://blog.naver.com/PostView.nhn?blogId=wonsiksnz&logNo=221536806966

**Comment by wonsiks** [comment]
Actually it's a kind of self-extracting compressed archive contains nodejs and npm installed lizgoban files.
It's for users who are using lizzie so lizgoban can use weights files from lizzie folder.
However it can be used standalone by editing main.js file in src folder for changing weights file location.

**Comment by kaorahi** [comment]
Ah, I see. Thx!

**Comment by ozymandias8** [comment]
I tried to run this as a standalone software in windows and cannot get it to work so far. I am trying to use KataGo with the katago config file. I am not familiar with the java language, so this is probably my fault somehow. 

`{
    "analyze_interval_centisec": 30,
    "wait_for_startup": false,
    "leelaz_command": "C:\KataGo\main.exe",
    "leelaz_args": ["gtp", "-model", "C:\KataGo\20b.txt", "-config", "C:\KataGo\configs\gtp_example.cfg"]
}`

lizgoban_windows is set to:

`Const conf = "katago.json"
command = "npx electron src"

Set fso = CreateObject("Scripting.FileSystemObject")
If fso.FileExists(conf) Then
command = command & " -c " & conf
End If

CreateObject("WScript.Shell").Run command, 0
`

When I run the script, I get the following error.

`[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
SyntaxError: Unexpected token K in JSON at position 99
    at JSON.parse (<anonymous>)
    at merge_json (C:\LizGoban\src\main.js:27:56)
    at parse_option (C:\LizGoban\src\main.js:36:16)
    at C:\LizGoban\src\main.js:25:35
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\LizGoban\src\main.js:25:14)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
`

**Comment by kaorahi** [comment]
@ozymandias8, let's move to #25. I'd like to use this issue for offering Windows binaries of lizgoban.

**Comment by ivysrono** [comment]
@ozymandias8 edit `\` to `\\`

**Comment by kaorahi** [comment]
implemented (3dfcc6f3)
