### ISSUE TITLE
Question: how would I implement receiving moves from a server?

### ISSUE THREAD

**Issue by ISibboI** [kaorahi/lizgoban#61]
I would like to hook up lizgoban to OGS to make every move of an OGS game appear live in lizgoban.

For that I would be able to do the OGS adapter part, but I do not know how I would make the necessary changes to lizgoban.

My main question is: How do I programmatically enter a move into lizgoban?

**Comment by kaorahi** [comment]
After 9ac351f4, you can control lizgoban from its STDIN as follows (example on Linux).

~~~
$ cd lizgoban/
$ echo 'mimic("play", "D3"); mimic("play", "R4")' | npm start -- -j '{"repl": true}'
~~~

See `const api = ...` in src/main.js for the list of commands. "Debug log" in "Debug" menu will be also useful if you want to observe which API is called for each mouse/keyboard operation. For debugging, you may prefer to type `mimic(...)` directly on the console with "REPL" in "Debug" menu.

Please note that this feature is experimental and API etc. may be changed in future.

Enjoy!

**Comment by ISibboI** [comment]
Cool thank you very much!

**Comment by qcgm1978** [comment]
Do I need to install any programs before running this command? I am getting the following error message when running it on my Mac:
<img width="848" alt="截屏2023-11-02 11 55 02" src="https://github.com/kaorahi/lizgoban/assets/3024299/a54486be-fcf5-4c29-9377-5cd35a91804e">

**Comment by kaorahi** [comment]
I think the message 'sysctlbyname ...' is unrelated to this feature. If you notice D3 and R4 stones on the board, the `mimic` command functions correctly.

Both 'undefined' and 'REPL is closed' messages indicate expected behaviors. The former means that the API returns nothing, while the latter shows that the `echo` command has finished and its pipe is closed.

**Comment by qcgm1978** [comment]
About the `mimic` method, I have some questions:

1. The application launched by the command does not use the face_image_rule customized in the config.json file in the root directory, but applies the settings in the external/config.json file.

2. The method "type mimic(...) directly on the console with "REPL" in "Debug" menu" is invalid. `C3` isn't played on the board.
<img width="654" alt="截屏2023-11-10 22 09 17" src="https://github.com/kaorahi/lizgoban/assets/3024299/89566e41-d85d-43a2-8d67-d80dc99cb7a2">

3. Can mimic be called in other ways besides running in the command line, such as Python? Can we switch to the project folder and run the command line using Python? Is this the correct way to use the interface?

**Comment by kaorahi** [comment]
(1)
`external/config.json` is the default path for the configuration file. The folder containing `LizGoban*.exe` is also checked in the case of the all-in-one package. See the definitions of `default_path_for`, `default_config_paths`, and `parse_argv` in option.js for details.

(2)
It seems that you are starting lizgoban using `echo ... | npm ...`. Please try just `npm start` without `echo` command. You can type any JS code after `LizGoban>` prompt. `echo` is not needed here. Just `mimic(...)` is OK.

(3)
Here is an example. You need d1fe0dfd0 or later.

```python
#!/bin/python3

import subprocess
import time

working_directory = '/PATH/TO/LIZGOBAN'
command = 'npm start -- -j \'{"repl": true}\''

process = subprocess.Popen(
    command,
    shell=True,
    stdin=subprocess.PIPE,
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
    text=True,
    cwd=working_directory,
)

process.stdin.write('mimic("play", "D3")\n')
process.stdin.flush()

time.sleep(3)

process.stdin.write('mimic("play", "R4")\n')
process.stdin.flush()

time.sleep(3)

process.stdin.write('app.quit()\n')
process.stdin.flush()

process.wait()
```

**Comment by qcgm1978** [comment]
You are right. I have been running `npm start -- -c config.json`, mistakenly thinking that the root directory is the default location of config.json.

`npm start` without echo command worked. However, running the debug mode in VS Code seems to not support the repl module.

The Python code also ran successfully. I need to further consider how to dynamically obtain data information for synchronous analysis.

Thanks for your guidance!

**Comment by qcgm1978** [comment]
Encountered a new issue:

The following method works in the command line:
```cmd
mimic('read_sgf','(;AP[golaxy]CA[UTF-8]KM[6.5]PB[金湊笌]PW[金珉舒]RE[B+R]SZ[19];B[pd];W[dp])')
```
However, it is invalid when running in Python. The sgf string would not be loaded.
```python
s='(;AP[golaxy]CA[UTF-8]KM[6.5]PB[金凑笌]PW[金珉舒]RE[B+R]SZ[19];B[pd];W[dp])'
command=f"mimic('read_sgf','{s}')"
self.process.stdin.write(command)
self.process.stdin.flush()
```

**Comment by kaorahi** [comment]
missing `\n`? This works for me.

```
command=f"mimic('read_sgf','{s}')\n"
```

**Comment by qcgm1978** [comment]
You're right. It works if `\n` added. What's more I have to replace all `\n` in sgf str if it has or it also doesn't work.
