### ISSUE TITLE
Ladder detection & auto-continuation

### ISSUE THREAD

**Issue by kaorahi** [kaorahi/lizgoban#63]
Isn't this fun? It will appear in the next release (0.6.0-pre1).
![ladder](https://user-images.githubusercontent.com/38910552/103169989-f5ff5880-4883-11eb-9e87-cf791142750a.gif)

When you play a few (at least two) ladder moves successively, possible ladder breakers are marked as "=". Push "=" key (keep holding down) to preview the continuation of the ladder. Hit Enter key to play it on another trial board in this preview. Once you have seen a ladder by "=" key, you can push "=" key again whenever you want to retry the same ladder on a different board situation (without "=" mark).

**Comment by hebaeba** [comment]
Can we visualize the Yomi of Ladder?
This could be fun!
