### ISSUE TITLE
can the project be deployed as a web service, and view through a browser?

### ISSUE THREAD

**Issue by xiaoyifang** [kaorahi/lizgoban#64]
if can ,the project can be deployed in a web server,you can visit it through browser everywhere.

**Comment by kaorahi** [comment]
@zakki wrote a browser version in the last year. You may be interested in it if you can prepare a web server by yourself.

https://github.com/zakki/lizgoban/tree/browser

Othewise, if you have a favorite feature in lizgoban, it will be rather hopeful to request existing online Go services to import it. I have no plan in this direction at all.

**Comment by zakki** [comment]
Blog(Japanese) https://matsuzaki.hatenadiary.org/entry/2019/10/27/111802
EC2 AMI oregon:ami-0f6a99179a0f6560a
