### ISSUE TITLE
no score estimation?

### ISSUE THREAD

**Issue by undefinedcodezhong** [kaorahi/lizgoban#65]
I follow the step as:
```
To use LizGoban with Leela Zero:

    Install Node.js v12 or later.
    Type git clone https://github.com/kaorahi/lizgoban; cd lizgoban; npm install on a terminal.
    Put Leela Zero binary (version 0.17 or later) as external/leelaz together with its network weight as external/network.gz.
    Type npm start. (Windows: Double-click lizgoban_windows.vbs.)

Use npm start -- --no-sandbox if you get an error like "The SUID sandbox helper binary was found, but is not configured correctly" and you do not want to fix it.
```
the external folder struct like this : 
.
├── e6e2e99bb732ae8e90aaa4f4ccc606ae5d38cd22f74681b11bea2b8a7ef3c3ae.gz
├── leela0110.rb
├── leelaz
├── network.gz
└── README.txt

the leelaz(binary file) is compiled from https://github.com/leela-zero/leela-zero, the network.gz file is renamed by e6e2e99bb732ae8e90aaa4f4ccc606ae5d38cd22f74681b11bea2b8a7ef3c3ae.gz which is downloaded from leela-zero.
But I can't get the ai analysis?
![Screenshot from 2021-02-10 16-25-10](https://user-images.githubusercontent.com/40236765/107485453-bdf76f00-6bbe-11eb-8e41-a7c4228ae1a6.png)

**Comment by kaorahi** [comment]
"waiting..." in the title bar suggests that lizgoban failed to detect initialization of the engine. When you start lizgoban, it executes `cd external; leelaz -g -w network.gz` internally and waits for the response `Detecting residual layers...`. So would you show the result of the following commands? (I assume Linux.)

~~~
cd external
./leelaz -g -w network.gz
(Hit ctrl-c after the initialization messages.)
~~~

my case:

~~~
$ cd external
$ ./leelaz -g -w network.gz
Using 8 thread(s).
RNG seed: 1026807630405287754
BLAS Core: built-in Eigen 3.3.7 library.
Detecting residual layers...v1...192 channels...15 blocks.
Initializing CPU-only evaluation.
Setting max tree size to 4324 MiB and cache size to 480 MiB.
^C
$ 
~~~

**Comment by undefinedcodezhong** [comment]
Thanks for your instant reply.
 The information shows me that my computer lack of OpenCL device (maybe my Leela bin is compiled by myself, so it's different from your CPU-only version). Luckily, it runs normally after I install the Nvidia OpenCL driver. Thank you so much!
![Screenshot from 2021-02-11 12-04-53](https://user-images.githubusercontent.com/40236765/107603122-bb505480-6c66-11eb-82c1-bcc196bc766b.png)

**Comment by kaorahi** [comment]
seems ok :)
