### ISSUE TITLE
Remote engine

### ISSUE THREAD

**Issue by dinohsu1019** [kaorahi/lizgoban#66]
Do you want to support remote engine (GTP) as Lizzie does? Thanks, Dino

**Comment by kaorahi** [comment]
If you are using a remote engine on Lizzie, the same command should work on LizGoban theoretically. Could you read `engine` in config.json in README?

Unfortunately, I cannot give you step-by-step instructions for Windows as I have no Windows machine.

**Comment by dinohsu1019** [comment]
![image](https://user-images.githubusercontent.com/30600848/109804495-449ee980-7c5d-11eb-8bc0-bdbcd61f05b5.png)
![image](https://user-images.githubusercontent.com/30600848/109804610-64cea880-7c5d-11eb-867e-28098c35bbe9.png)
@kaorahi, Lizzie has the "engine command", while Lizgoban has multiple parameters, I am not sure how to configure the latter for remote engine.

**Comment by kaorahi** [comment]
like this :)

~~~
            "engine": ["plink.exe", "-ssh", "-pw", ...]
~~~

If you need more help, please paste "engine-command" line of Lizzie's config.txt as a text (not as a screenshot image).

**Comment by dinohsu1019** [comment]
@kaorahi, here's the "engine-command" in text (including quotation marks but not the ending comma)

"plink.exe -ssh -pw ssh_in -P 22222 ssh_in@58.115.137.108 C:/katago-v1.7.0-gpu-cuda10.2-windows-x64/katago.exe gtp -config C:/katago-v1.7.0-gpu-cuda10.2-windows-x64/my_gtp.cfg -model C:/katago-v1.7.0-gpu-cuda10.2-windows-x64/my_katago_40b.gz"

Please help to show the right configuration for Lizgoban, thanks again.

**Comment by kaorahi** [comment]
Then this is the corresponding setting in lizgoban.

~~~
            "engine": ["plink.exe", "-ssh", "-pw", "ssh_in", "-P", "22222", "ssh_in@58.115.137.108",
                       "C:/katago-v1.7.0-gpu-cuda10.2-windows-x64/katago.exe", "gtp",
                       "-config", "C:/katago-v1.7.0-gpu-cuda10.2-windows-x64/my_gtp.cfg",
                       "-model", "C:/katago-v1.7.0-gpu-cuda10.2-windows-x64/my_katago_40b.gz"]
~~~

**Comment by dinohsu1019** [comment]
@kaorahi It works now!! The only additional point to rectify is the the first command plink.exe should be with full path, namely C:/Program Files/PuTTY/plink.exe. Thanks a lot.

**Comment by kaorahi** [comment]
happy to hear it :)
