### ISSUE TITLE
Solve tsumego pictures (demo)

### ISSUE THREAD

**Issue by kaorahi** [kaorahi/lizgoban#68]
I'm trying semiautomatic import of diagram images, that will appear in the next release. It is useful for trying tsumego pages, e.g.

* [Eba tsumego](https://www.h-eba.com/heba/tumego/eba.html)
* [Basic life/death dictionary](https://www.h-eba.com/heba/JITEN/jiten0-4.html)

![tsumego_image](https://user-images.githubusercontent.com/38910552/112742965-23b48480-8fce-11eb-8e9e-b93a1c33c8ec.gif)

**Comment by hebaeba** [comment]
Thank you for citing my book.
It's fun to think that LizGoban's Tsumego features will be further enhanced.
I look forward to the next release.

**Comment by kaorahi** [comment]
thx :)

...and here is an [online version of "SGF from Image"](http://kaorahi.github.io/lizgoban/src/sgf_from_image/sgf_from_image.html).

**Comment by kaorahi** [comment]
released as 0.6.1
