### ISSUE TITLE
What does Lizzie-style real-time mean? Ponder On?

### ISSUE THREAD

**Issue by HackYardo** [kaorahi/lizgoban#72]
Half of the Go/Baduk/Weiqi GUIs on Github are Lizzie-style. My laptop(uhd620+mx110) can run them but the temperature are up to ~90 °C. It's too hot and too stuck to play games. I don't know why. The graphics are too old, so incompatible? The graphics are too cheap, so small?

**Comment by kaorahi** [comment]
I'm not sure what you are asking...

If you expect technical supports on the engines and other GUIs, here is not a suitable place. If you really have an issue on lizgoban, would you describe it clearly without abbreviation, indirect wording, etc.?
