### ISSUE TITLE
Show KataGo ownership without numbers

### ISSUE THREAD

**Issue by raylu** [kaorahi/lizgoban#74]
currently, the app shows ownership with `shift+e` (or view > ownership) with green and pink numbers in each region (boundaries shown when holding `v`) like in the screen recording in the readme:
![screen recording](https://raw.githubusercontent.com/kaorahi/lizgoban/master/screen.gif)

the 0.7.0-pre2 releases page shows a screenshot with just per-point ownership info in a single color (red)
![screenshot](https://user-images.githubusercontent.com/38910552/138873127-31cfed50-6ecb-4f79-aefd-3d7a06318df9.png)
I'm not sure how to get this mode. (I'm also not sure how to interpret this; shouldn't there be 2 colors?)

assuming this mode isn't currently possible to get, would you accept a PR to turn off the green and pink numbers?

**Comment by kaorahi** [comment]
The second screenshot is not the ownership but the standard deviation of the ownership. It is shown in the subboard by default.

There is no way to show the ownership without the green/pink numbers at present. Before considering the option to hide them, I'd like to ask...

Have you tried katrain or lizzie? They can show the ownership more beautifully. Do you have a reason why you dare to use lizgoban?

**Comment by raylu** [comment]
haha, actually I normally use lizzie. I just tried lizgoban yesterday and I've played around with katrain a little previously. lizzie seems like a dead project at this point, so I'm looking to switch to something else

**Comment by kaorahi** [comment]
:-)

(Though implementation of this issue is easy (e1db84e3e), I'd like to defer it until it is really needed. Apps tend to be buggy if they have too many options that are not used by the developers themselves actually.)
