### ISSUE TITLE
feature request: switch engine and weight by key

### ISSUE THREAD

**Issue by ivysrono** [kaorahi/lizgoban#8]
from lizzie: https://github.com/featurecat/lizzie/wiki/Lizzie-v0.6-Simple-Manual-(draft)#new-key-cutshort

This feature need to separate settings, just like sabaki's settings.json or lizzie's config.txt, which users can store engines.

**Comment by kaorahi** [comment]
You can switch the weigths to LZ227 by F1 key and to ELF2 by F2 key in 1a88dd40 as follows. This is quite experimental and it may be changed in future.

~~~
npx electron src -j '{"shortcut": [{"label": "LZ227", "accelerator": "F1", "option": {"leelaz_args": ["-g", "-w", "/foo/bar/LZ227.gz"]}}, {"label": "ELF2", "accelerator": "F2", "option": {"leelaz_args": ["-g", "-w", "/foo/bar/ELF2.gz"]}}]}'
~~~

I cannot decide to introduce a config file at present since it seems too difficult for most Go players. It may be better to use another UI, for example, Shift+F1 (assign the current weights file to F1 key) and F1 (switch the weights to the assigned one).

**Comment by kaorahi** [comment]
...though this -j is much more difficult than a config file :p

**Comment by ivysrono** [comment]
![图片](https://user-images.githubusercontent.com/2649544/59153770-03cc6d80-8a95-11e9-9a7c-e8fc4015f766.png)
We can change weights by UI:
![图片](https://user-images.githubusercontent.com/2649544/59153786-468e4580-8a95-11e9-8eda-241207c4ea99.png)
However, we need change engines for [minigo-v17](https://github.com/leela-zero/leela-zero/issues/2380#issuecomment-491131296) or [PhoenixGo](https://github.com/yenw/LeelaZero_PhoenixGo)

**Comment by kaorahi** [comment]
The above -j is obsolete after 288f2067. See below (F1 key = LZ, F2 key = minigo). This is still experimental and undocumented.

~~~
npx electron src -j '{"shortcut": [{"label": "LZ", "accelerator": "F1", "leelaz_command": "/foo/bar/leelaz", "leelaz_args": ["-g", "-w", "/foo/bar/LZ227.gz"]}, {"label": "minigo", "accelerator": "F2", "leelaz_command": "/foo/bar/leelaz_minigo", "leelaz_args": ["-g", "-w", "/foo/bar/990.gz"]}]}'
~~~

**Comment by kaorahi** [comment]
I recognized that [double quotes are troublesome](https://stackoverflow.com/questions/7760545/escape-double-quotes-in-parameter) in Windows. So I introduced a config file in ccf9c9df.

~~~
npx electron src -c config.json
~~~

Example of config.json:

~~~
{
  "shortcut": [
    {
      "label": "LZ",
      "accelerator": "F1",
      "leelaz_command": "/foo/bar/leelaz",
      "leelaz_args": ["-g", "-w", "/foo/bar/LZ227.gz"]
    },
    {
      "label": "minigo",
      "accelerator": "F2",
      "leelaz_command": "/foo/bar/leelaz_minigo",
      "leelaz_args": ["-g", "-w", "/foo/bar/990.gz"]
    }
  ]
}
~~~

**Comment by ivysrono** [comment]
thanks, work fine:
```
{
  "shortcut": [
    {
      "label": "LZ",
      "accelerator": "ctrl+1",
      "leelaz_command": "D:\\AI\\leela-zero\\leelaz.exe",
      "leelaz_args": ["-g", "-w", "D:\\AI\\Weights\\10B_ManKitPong"]
    },
    {
      "label": "minigo",
      "accelerator": "ctrl+2",
      "leelaz_command": "D:\\AI\\leela-zero\\leelaz.exe",
      "leelaz_args": ["-g", "-w", "D:\\AI\\Weights\\15B_LeelaMaster_GX89"]
    }
  ]
}
```

**Comment by ivysrono** [comment]
Just one more thing: could I set default leelaz_command and args in config.json ?

**Comment by kaorahi** [comment]
I implemented your proposal with a slight modification in 7a460f96. The first item in "shortcut: [...]" is used as the initial setting now.

**Comment by ivysrono** [comment]
thanks
