### ISSUE TITLE
Rules are not applied property after recent updates

### ISSUE THREAD

**Issue by isty2e** [kaorahi/lizgoban#87]
It would seem like Chinese (or TT) rule is used even if the rule is set to Japanese on the GUI. The UI tells me that the ruleset is Japanese, but judging by the winrates and such, I am quite sure that it is actually one of Chinese-like rules. I pull the repo on a monthly basis, so this problem shouldn't be older than a month, I suppose.

**Comment by kaorahi** [comment]
thx for the report! It is fixed in 14128bc3f and I will release v0.8.0-pre3 soon.
