### ISSUE TITLE
Next move colour error

### ISSUE THREAD

**Issue by DaviidM** [kaorahi/lizgoban#89]
Perhaps not something you have considered but... 

I am using LizGoBan (0.8.0-pre3_win_230714a) to analyse problems for my students.  The example .sgf below is a problem example including the answer.  The problem is White to play and the answer is in the .sgf.  The LizGoBan analysis works fine with the White move on the board but when I go back a move (removing the Whtite stone from the board), LizGoBan still considers Black has sente. 

Example .sgf
(;GM[1]FF[3]SZ[19]AP[SmartGo:3.1.8]CA[UTF-8]
GN[Leaflet 748 A4]
DT[2023-06-24]
KM[6.5]
RU[Japanese]ST[2]
AB[bp][cm][co][cp][dn][dp][dr][eq][er][lc][nq][od][pq][qd][qo][qp]
AW[bq][ck][cq][dd][dl][dm][dq][en][eo][ep][jd][pm][po][qi][qn]
PL[B]
C[White to play]LB[qf:A][df:B][ke:C][fd:D]
(;W[df])
(;W[ke];B[cf];W[be];B[ef];W[fd];B[dj]))

**Comment by kaorahi** [comment]
Your SGF has the property "PL[B]", that explicitly specifies "black to play". "PL[W]" seems correct for "white to play".

Be that as it may, you might prefer using other GUIs for this purpose because lizgoban is not convenient for such a branched SGF and it does not support "LB" property.

**Comment by DaviidM** [comment]
Thank you.
