### ISSUE TITLE
feature request: remove red lines

### ISSUE THREAD

**Issue by ivysrono** [kaorahi/lizgoban#9]
![图片](https://user-images.githubusercontent.com/2649544/59158741-63586680-8af1-11e9-9caf-17a8c7d5e608.png)
I don't think these red lines have any practical meaning, but they cause visual interference. I want to get rid of them by config.

**Comment by kaorahi** [comment]
The red lines were removed in Lizzie style (bf65709d). BTW, I'm interested in the reason why you use lizgoban if you prefer Lizzie style.

**Comment by ivysrono** [comment]
I hate java 😭
