### ISSUE TITLE
Why katago not connected when running?

### ISSUE THREAD

**Issue by qcgm1978** [kaorahi/lizgoban#90]
The electron app shows katago waiting all the time. My config.json is:
```json
"preset": [
    {
      "label": "KataGo",
      "engine": [
        "/opt/homebrew/Cellar/katago/1.13.2/bin/katago",
        "gtp",
        "-override-config",
        "analysisPVLen=50, defaultBoardSize=19",
        "-model",
        "/opt/homebrew/Cellar/katago/1.13.2/share/katago/kata1-b18c384nbt-s7342816768-d3618704537.bin.gz",
        "-config",
        "/opt/homebrew/Cellar/katago/1.13.2/share/katago/configs/analysis_example.cfg"
      ]
    }
]
```
I run the npm command `npm start -- -c config.json`

Electron app:
<img width="955" alt="截屏2023-09-18 21 04 31" src="https://github.com/kaorahi/lizgoban/assets/3024299/acb990d8-18da-4eba-92fa-f5f466f21d91">

**Comment by kaorahi** [comment]
Does the following command work in your terminal (shell)?

```
/opt/homebrew/Cellar/katago/1.13.2/bin/katago gtp -override-config "analysisPVLen=50, defaultBoardSize=19" -model /opt/homebrew/Cellar/katago/1.13.2/share/katago/kata1-b18c384nbt-s7342816768-d3618704537.bin.gz -config /opt/homebrew/Cellar/katago/1.13.2/share/katago/configs/analysis_example.cfg
```

You should see the following message if it works correctly. (Press Ctrl-C to terminate it.)

```
GTP ready, beginning main protocol loop
```

**Comment by qcgm1978** [comment]
Thanks. You're right. I try the command and terminal prompts some config missing e.g.  logAllGTPCommunication, logSearchInfo and so on. So I change the config file to `gtp_example.cfg` and it works.

Thanks a lot.
