### ISSUE TITLE
Can you train a katago that goes down 2 steps in a row?

### ISSUE THREAD

**Issue by awsjgy** [kaorahi/lizgoban#93]
China Wildfox Go platform, Flying Dagger game, supports 2 moves in a row. 11 x 11 paths

**Comment by kaorahi** [comment]
It seems to cause significant changes to the game strategy, going far beyond just a GUI modification. So it is out of the scope of this project.

**Comment by awsjgy** [comment]
> It seems to cause significant changes to the game strategy, going far beyond just a GUI modification. So it is out of the scope of this project.
Yes, he needs to modify the algorithm.
Here's the thing, there's a game called Flying Daggers on the Chinese Wildfox Go gaming platform. It started about 2 years ago. It used to be a 9-way board, but now it's been updated to an 11-way board, and there are levels of play. The highest level is Blade God > Blade Immortal > Blade Saint, etc... I would like to modify the code to implement this rule. There is definitely more to this playstyle than just luck, as I've seen would-be players win 10 or so games in a row even at the highest rank. I'd like to train a katago with this rule.
是的，他需要修改算法。
是这样，在中国野狐围棋对弈平台，有个叫飞刀游戏的玩法。大概在2年前就开始了，之前是9路棋盘，现在更新到11路棋盘，而且有升降级玩法。最高等级是刀神>刀仙>刀圣 等。我想修改代码，实现这个规则。这个玩法绝对不只是运气，因为我见过会玩的即使到了最高等级也可以连胜10几盘。我想训练一个这样规则下的katago

**Comment by awsjgy** [comment]
> 它似乎对游戏策略造成了重大变化，远远超出了GUI修改的范围。所以它超出了这个项目的范围。

Can you make a gui that supports the next 2 steps?
你可以做一个支持下2步的gui吗？
