### ISSUE TITLE
Why are keyboard default events disabled?

### ISSUE THREAD

**Issue by qcgm1978** [kaorahi/lizgoban#99]
I found that many keyboard events are not working in electron applications. The code seems to have disabled the related events, such as copy and paste. Although I tried to change some of the configurations in the code,

```js
item('Copy SGF', 'CmdOrCtrl+Shift+C', () => copy_sgf_to_clipboard(false), true),
```

the system default Cmd+C,Cmd+V is still not working. Since I need to do copy and paste operations in the devtools frequently, this disabling of the default behavior causes a lot of inconvenience.

**Comment by kaorahi** [comment]
Hmm, this works for me:

* ctrl+C to copy something somewhere.
* npm start
* ctrl+shift+I to show the dev tools.
* Click the console in the dev tools to focus and confirm that the cursor appears there. (Important!)
* ctrl+V to paste something.

**Comment by qcgm1978** [comment]
It doesn't work for me. Maybe I add `win.webContents.openDevTools()` in main.js. At last I found it need comment out `Menu.setApplicationMenu(menu_for_window(win))`
